# Generated by Django 4.2.5 on 2023-09-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titile',
            new_name='title',
        ),
    ]
